baseURL = "https://teamtact.github.io/notesbase/"
languageCode = "en-us"
title = "TACT Author"
theme = "berbera"

pygmentsCodeFences=true
pygmentsUseClasses=true
canonifyURLs=true
publishDir="docs"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]
